# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JEDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 5.0.0-beta.3'
    pod 'MBProgressHUD'
    pod 'RealmSwift'		

  # Pods for JEDemo

  target 'JEDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JEDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
